# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('decision_type', models.CharField(choices=[('O', 'Ordinance'), ('R', 'Resoluation')], max_length=1)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('discussion', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=256, null=True)),
                ('mover', models.CharField(blank=True, max_length=256, null=True)),
                ('seconder', models.CharField(blank=True, max_length=256, null=True)),
                ('ayes', models.CharField(blank=True, max_length=1024, null=True)),
                ('nays', models.CharField(blank=True, max_length=1024, null=True)),
                ('abstains', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
